version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pipeline_db
    restart: always
    environment:
      POSTGRES_DB: video_pipeline
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root895
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: